version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        - BOT_TOKEN=${BOT_TOKEN}
        - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
        - MONGO_URI=${MONGO_URI}
    ports:
      - "5000:5000"

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
      args:
        - BOT_TOKEN=${BOT_TOKEN}
        - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID}

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
